app:
  name: Pauls Bogart App
  asset:
    servers: ['d1f7kn811ho9qg.cloudfront.net']
bogart:
  setting:
    dbinit: false
    log: true
    timer: true
    debug: true
db:
  connection: 'mongodb://localhost:27017,localhost:27018'
  dbname: Bogart